
name: Run PHP Script

on:
  schedule:
    - cron: "*/1 * * * *"
      timezone: "Asia/Kolkata"
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Execute PHP script
        run: php daily-script.php
