name: Run PHP Script

on:
  schedule:
    - cron: "2-59/5 * * * *"
  workflow_dispatch:

concurrency:
  group: run-php
  cancel-in-progress: false

jobs:
  run-php:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Execute PHP script
        run: php daily-script.php
